name: 'CI'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz gcovr libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-test-dev
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Build
        run: |
          cmake .
          cmake --build .

      - name: Test
        run: ctest

      - name: Coverage
        run: |
          mkdir code-coverage-report
          gcovr --root . --print-summary --html-details -o code-coverage-report/coverage.html --exclude-unreachable-branches -e .*tst_
      
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: code-coverage-report

      - name: Upload html docs
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/html
  
  deploy:
    if: github.ref_name == 'main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: html-docs

      - name: Deploy html docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
