name: 'Build and test'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y gcovr libboost-test-dev
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Build
        run: |
          cmake .
          cmake --build .

      - name: Test
        run: ctest

      - name: Coverage
        run: |
          mkdir code-coverage-report
          gcovr --root . --print-summary --html-details -o code-coverage-report/coverage.html --exclude-unreachable-branches -e .*tst_
      
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: code-coverage-report
